# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mod <- function(x, base) {
    .Call(`_incon_mod`, x, base)
}

get_index <- function(x, index, offset) {
    .Call(`_incon_get_index`, x, index, offset)
}

cosine_similarity_cpp <- function(x, template_, offset) {
    .Call(`_incon_cosine_similarity_cpp`, x, template_, offset)
}

sweep_template_cpp <- function(x, template_) {
    .Call(`_incon_sweep_template_cpp`, x, template_)
}

